######################################################################
# Automatically generated by qmake (3.0) Thu Nov 24 03:05:44 2016
######################################################################

TEMPLATE = app
TARGET = mcp3008Spi
INCLUDEPATH += .

# Input
HEADERS += mcp3008Spi.h
SOURCES += mcp3008Spi.cpp mcp3008SpiTest.cpp
